namespace: 
  name: sandbox

service: 
  name: techtrends
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
  labels: 
    app: techtrends

name: techtrends
image: 
  repository: phanan1608/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources: 
  requests: 
    cpu: 250m
    memory: 64Mi
  limits: 
    cpu: 500m
    memory: 128Mi

containerPort: 3111

livenessProbe: 
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111
