name: TechTrends - Package with Docker

# Trigger on every push to the main branch
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    # Run the action on the ubuntu-latest operating system
    runs-on: ubuntu-latest

    # A sequence of steps that will run to make sure we can build and push our image
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2

        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./project/techtrends
          file: ./project/techtrends/Dockerfile
          platforms: linux/amd64
          push: true
          tags: phanan1608/techtrends:latest